### ISSUE TITLE
Decide on future of "run.sh"

### ISSUE THREAD

**Issue by oybed** [rht-labs/labs-ci-cd#3]
Should just document the use of Ansible and avoid a wrapper .sh that could drive the wrong behavior.

**Comment by InfoSec812** [comment]
My opinion is to expand the `run.sh` to do some validation.

- Check for existence of `ansible-playbook` command
- Check for existence of `ansible-galaxy`
- Verify OCP presence
- Vertify cluster connectivity
  - On failure, prompt the user  for credentials

Each of these would have helpful error messages on failure so that the barriers to entry are low. This way, people who are not already extremely familiar with ansible/OCP could get this up and running without too much difficulty.
